# Generated by Django 5.1.7 on 2025-04-02 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioCadop',
            fields=[
                ('registro_ans', models.IntegerField(primary_key=True, serialize=False, verbose_name='Registro ANS')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('modalidade', models.CharField(max_length=255, verbose_name='Modalidade')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('ddd', models.CharField(blank=True, max_length=2, null=True, verbose_name='DDD')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('endereco_eletronico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Eletrônico')),
                ('representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Representante')),
                ('cargo_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo Representante')),
                ('regiao_de_comercializacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região de Comercialização')),
                ('data_registro_ans', models.CharField(max_length=10, verbose_name='Data Registro ANS')),
            ],
            options={
                'verbose_name': 'Relatório Cadop',
                'verbose_name_plural': 'Relatórios Cadop',
                'db_table': 'relatorio_cadop',
            },
        ),
        migrations.CreateModel(
            name='DemonstracoesContabeis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('cd_conta_contabil', models.IntegerField(verbose_name='Código Conta Contábil')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('vl_saldo_inicial', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Saldo Inicial')),
                ('vl_saldo_final', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Saldo Final')),
                ('reg_ans', models.ForeignKey(db_column='reg_ans', on_delete=django.db.models.deletion.CASCADE, to='api.relatoriocadop', verbose_name='Registro ANS')),
            ],
            options={
                'verbose_name': 'Demonstração Contábil',
                'verbose_name_plural': 'Demonstrações Contábeis',
                'db_table': 'demonstracoes_contabeis',
            },
        ),
    ]
